if (!isServer) exitWith {false};
params [["_itemId", "", [""]], ["_quantity", 1, [0]]];
private _owner = remoteExecutedOwner;
private _player = allPlayers select {owner _x == _owner} param [0, objNull];
if (isNull _player) exitWith {false};
_quantity = floor _quantity;
if (_quantity < 1 || {_quantity > 100}) exitWith {false};
private _cfg = missionNamespace getVariable ["RHD_LifeCore_Config", createHashMap];
private _items = [_cfg getOrDefault ["shopCatalog", ""]] call RHD_fnc_parseList;
private _entry = _items select {toLower (_x param [0, ""]) isEqualTo toLower _itemId} param [0, []];
if (count _entry < 4) exitWith {false};
private _unitPrice = (parseNumber (_entry select 3)) max 0;
private _uid = getPlayerUID _player;
private _profiles = missionNamespace getVariable ["RHD_LifeCore_ServerProfiles", createHashMap];
private _profile = _profiles getOrDefault [_uid, createHashMap];
if (count _profile == 0) exitWith {false};
private _inventory = _profile getOrDefault ["inventory", []];
private _idx = _inventory findIf {(_x select 0) isEqualTo _itemId};
if (_idx < 0) exitWith {false};
private _owned = _inventory select _idx select 1;
if (_quantity > _owned) exitWith {false};
private _remaining = _owned - _quantity;
if (_remaining <= 0) then {_inventory deleteAt _idx;} else {_inventory set [_idx, [_itemId, _remaining]];};
_profile set ["inventory", _inventory];
_profile set ["cash", (_profile getOrDefault ["cash", 0]) + (_unitPrice * _quantity)];
_profiles set [_uid, _profile];
missionNamespace setVariable ["RHD_LifeCore_ServerProfiles", _profiles];
_player setVariable ["RHD_RP_Inventory", _inventory, true];
_player setVariable ["RHD_RP_Cash", _profile get "cash", true];
[_player] call RHD_fnc_serverSaveProfile;
true